name: Devolv Action Test

on:
  push:
    branches:
      - main    # Adjust if you're using a different default branch
  workflow_dispatch: {}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:

  test-devolv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::149704127940:role/devolv-DevolvRole
          aws-region: us-east-1

      - name: Run Devolv Drift
        uses: devolvdev/devolv-actions@v2
        with:
          tool: drift
          policy-name: DevolvTestPolicyHuge
          path: ./test-devolv-policy.json
          approvers: RkSinghDeo
          github-token: ${{ secrets.GITHUB_TOKEN }}
          approval-anyway: true
        
      - name: Run Devolv Validate
        uses: devolvdev/devolv-actions@v2
        with:
          tool: validate
          path: ./test-devolv-policy.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
